import { action } from '@storybook/addon-actions';
import type { Meta, StoryObj } from '@storybook/angular';
import { argsToTemplate, componentWrapperDecorator } from '@storybook/angular';
import { ProductFeatureListTableComponent } from './product-feature-list-table.component';


export const actionsData = {
  featureMoved: action('featureMoved'),
  optionMoved: action('optionMoved'),
  featureDeleted: action('featureDeleted'),
  optionDeleted: action('optionDeleted'),
  optionsActivated: action('optionsActivated'),
  optionsDeactivated: action('optionsDeactivated'),
  optionsReleasedToFactory: action('optionsReleasedToFactory'),
  optionsUnreleasedFromFactory: action('optionsUnreleasedFromFactory'),
  featureAnalyzerOpened: action('featureAnalyzerOpened'),
  featureImporterOpened: action('featureImporterOpened'),
  optionImporterOpened: action('optionImporterOpened'),
};

const meta: Meta<ProductFeatureListTableComponent> = {
  title: 'Product Feature List Table',
  component: ProductFeatureListTableComponent,
  excludeStories: /.*Data$/,
  tags: ['autodocs'],
  parameters: {
    componentSubtitle:
      'Product Feature List Table',
  },
  decorators: [
    componentWrapperDecorator((story) => `<div style="height: 500px; width: 100%; display:flex">${story}</div>`)
  ],
  render: (args: ProductFeatureListTableComponent) => ({
    props: {
      ...args,
      featureMoved: actionsData.featureMoved,
      optionMoved: actionsData.optionMoved,
      featureDeleted: actionsData.featureDeleted,
      optionDeleted: actionsData.optionDeleted,
      optionsActivated: actionsData.optionsActivated,
      optionsDeactivated: actionsData.optionsDeactivated,
      optionsReleasedToFactory: actionsData.optionsReleasedToFactory,
      optionsUnreleasedFromFactory: actionsData.optionsUnreleasedFromFactory,
      featureAnalyzerOpened: actionsData.featureAnalyzerOpened,
      featureImporterOpened: actionsData.featureImporterOpened,
      optionImporterOpened: actionsData.optionImporterOpened
    },
    template: `<csps-product-feature-list-table ${argsToTemplate(args)}></csps-product-feature-list-table>`,
  }),
};

export default meta;
type Story = StoryObj<ProductFeatureListTableComponent>;

/**
 * Default usage of the burn down chart
 */
export const Default: Story = {
  args: {
    features: [
      {
        id: '1', category: { name: 'A' }, name: 'Feat 1', description: 'F1', rank: 'fdsf', notes: 'ABC', options: [
          { id: '11', name: 'option11', description: 'desc11', rank: 'sdf', isActive: true, releases: [], isAutoGenerated: false },
          { id: '12', name: 'option12', description: 'desc12', rank: 'aaa', isActive: true, releases: [], isAutoGenerated: false },
        ]
      },
      {
        id: '2', category: { name: 'B' }, name: 'Feat 2', description: 'F2', rank: 'dsf', notes: 'ABC', options: [
          { id: '21', name: 'option21', description: 'desc21', rank: 'edc', isActive: true, releases: [], isAutoGenerated: false },
          { id: '22', name: 'option22', description: 'desc22', rank: 'sqs', isActive: true, releases: [], isAutoGenerated: false }
        ]
      },
      {
        id: '3', category: { name: 'A' }, name: 'Feat 3', description: 'F3', rank: 'edc', notes: 'ABC', options: [
          { id: '31', name: 'option31', description: 'desc31', rank: 'lkj', isActive: true, releases: [], isAutoGenerated: false },
          { id: '32', name: 'option32', description: 'desc32', rank: 'ert', isActive: true, releases: [], isAutoGenerated: false }
        ]
      },
    ],
    dimensions: [],
    factories: [
      { id: '1', name: 'San Antonio', abbreviation: 'SAT' },
      { id: '2', name: 'Nantes', abbreviation: 'NAN' },
      { id: '3', name: 'Wuxi', abbreviation: 'WXF' }
    ],
    styles: [
      { id: '1', name: 'A' },
      { id: '2', name: 'B' },
    ]
  },
};
