export interface Colors {
  'blue': string,
  'indigo': string,
  'purple': string,
  'pink': string,
  'red': string,
  'orange': string,
  'yellow': string,
  'green': string,
  'teal': string,
  'cyan': string,
  'white': string,
  'gray': string,
  'gray-dark': string,
  'primary': string,
  'secondary': string,
  'success': string,
  'info': string,
  'warning': string,
  'danger': string,
  'light': string,
  'dark': string
}
